# Generated by Django 4.1.2 on 2022-10-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="products",
            unique_together={("product_id", "product_name")},
        ),
    ]
