# Generated by Django 4.1.2 on 2022-10-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_products_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="products",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="products",
            name="product_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
